### PR TITLE
added summary diagnostic modes

### PR DESCRIPTION
**Pull request by AlexHaxe**
added `markiscodecoverage.detailCoverageMode` and `markiscodecoverage.summaryWithCurly` config parameters
users can choose to have detailed diagnostics for all files (default == behaviour of previous versions), only for open files, only for active files or for no files. 
Files without detailed diagnostics show a single summary diagnostic message using a range from first uncovered line to last.

When using `never` for `markiscodecoverage.detailCoverageMode`, setting `markiscodecoverage.summaryWithCurly = false` will minimise curly underlining of uncovered code.

### CODE REVIEW

**Comment by AlexHaxe** [comment]
I guess that's a no.

**Comment by markis** [comment]
Sorry, it was old and had conflicts.  I wasn't sure if you still used the extension.

**Comment by AlexHaxe** [comment]
I guess you're right. I haven't been using your extension for a while and my PR / diff is a mess because of not keeping it up-to-date.
so closing without merge is probably the only sensible option.

**Comment by markis** [comment]
Thanks for the contributions!  All the best!

**Pull request closed without merging**
